(deftheme vitesse-dark
  "Created 2023-03-20. Port of the VS Code theme https://github.com/antfu/vscode-theme-vitesse")

(defvar 'color

(custom-theme-set-faces
 'Vitesse Dark
 '(default ((t (:family "Fira Code" :foundry "nil" :width normal :height 120 :weight normal :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#ABB2BF" :background "#282C34" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#121212"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#61AFEF"))))
 '(highlight ((t (:background "#2C323C"))))
 '(region ((t (:extend t :inverse-video nil :background "#3E4452"))))
 '(shadow ((t (:foreground "#5C6370"))))
 '(secondary-selection ((t (:extend t :background "#3E4452"))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-builtin-face ((t (:foreground "#cb7676"))))
 '(font-lock-comment-delimiter-face ((t (:slant italic :foreground "#ff9900"))))
 '(font-lock-comment-face ((t (:slant italic :foreground "#ff9900"))))
 '(font-lock-constant-face ((t (:foreground "#c99076"))))
 '(font-lock-doc-face ((t (:foreground "#5C6370"))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-function-name-face ((t (:foreground "#80a665"))))
 '(font-lock-keyword-face ((t (:foreground "#4d9375"))))
 '(font-lock-negation-char-face ((t (:foreground "#61AFEF"))))
 '(font-lock-preprocessor-face ((t (:foreground "#E5C07B"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#E5C07B"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#C678DD"))))
 '(font-lock-string-face ((t (:foreground "#c98a7d"))))
 '(font-lock-type-face ((t (:foreground "#61AFEF"))))
 '(font-lock-variable-name-face ((t (:foreground "#bd976a"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#BE5046"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line)))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:foreground "#636D83" :background "#292E37"))))
 '(header-line ((t (:foreground "#D19A66" :inherit (mode-line-inactive)))))
 '(tooltip ((t (:inverse-video t :foreground "#E5C07B" :background "#282C34"))))
 '(mode-line ((t (:weight normal :box (:line-width (1 . 1) :color "#2C323C" :style nil) :foreground "#ABB2BF" :background "#2C323C"))))
 '(mode-line-buffer-id ((t (:foreground "#ABB2BF"))))
 '(mode-line-emphasis ((t (:slant italic :foreground "#ABB2BF"))))
 '(mode-line-highlight ((t (:weight bold :box nil :foreground "#C678DD"))))
 '(mode-line-inactive ((t (:weight normal :foreground "#5C6370" :background "#3E4452" :inherit (mode-line)))))
 '(isearch ((t (:weight normal :foreground "#282C34" :background "#E06C75"))))
 '(isearch-fail ((t (:weight bold :foreground "#E5C07B" :background "#282C34"))))
 '(lazy-highlight ((t (:weight normal :foreground "#282C34" :background "#E5C07B"))))
 '(match ((t (:weight bold :foreground "#528BFF" :background "#282C34"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'vitesse-dark)
